repos:
-   repo: local
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=500']
        exclude: ^projects/pilot/configs/datasets/
        name: Check added large files.
        entry: check-added-large-files
        language: system
-   repo: local
    hooks:
    -   id: end-of-file-fixer
        name: Fix end-of-file
        entry: end-of-file-fixer
        language: system
        types: [python]
-   repo: local
    hooks:
    -   id: trailing-whitespace
        name: Trailing whitespace
        entry: trailing-whitespace-fixer
        language: system
        types: [python]
-   repo: local
    hooks:
    -   id: check-merge-conflict
        name: Check merge conflict
        entry: check-merge-conflict
        language: system
        types: [python]
-   repo: local
    hooks:
    -   id: check-docstring-first
        name: Check docstring first
        entry: check-docstring-first
        language: system
        types: [python]
-   repo: local
    hooks:
    -   id: isort
        name: Check python imports.
        entry: isort --filter-files
        language: system
        types: [python]
-   repo: local
    hooks:
    -   id: black
        name: Auto format python code.
        entry: black -l 79
        language: system
        types: [python]
-   repo: local
    hooks:
    -   id: flake8
        name: Check pep8.
        entry: flake8
        language: system
        types: [python]
-   repo: local
    hooks:
    -   id: pydocstyle
        name: Check docstring.
        entry: pydocstyle
        language: system
        files: (?x)(^prediction/tmp/)
        types: [python]

# -   repo: local
#     hooks:
#     -   id: import-linter
#         name: import-linter
#         description: Import Linter allows you to define and enforce rules for the internal and external imports within your Python project.
#         entry: lint-imports
#         language: python
#         types: [python]
#         pass_filenames: false
